### ISSUE TITLE
Add linker map support

### ISSUE THREAD

**Issue by HiFiPhile** [hirdrac/makefile#3]
I'v tried it for cross compile in a bare-matal application and it works well, for this I need linker map to analyze flash usage, so I added:
```
BIN1.LINK_FLAGS = \
    $(COMMON_LINK_FLAGS) \
    -Wl,-Map=$(BIN1).map \
```

However while cleaning it complains:
```
$ make clean
Cleaning 'build/release-BIN1'
Cleaning 'build/debug-BIN1'
rmdir: failed to remove 'build/release-BIN1': Directory not empty
rmdir: failed to remove 'build/debug-BIN1': Directory not empty
rmdir: failed to remove 'build': Directory not empty
```

Could you please add linker map generation support ?

**Comment by hirdrac** [comment]
I tried to be clever and change to the build directory before linking so I wouldn't need the build directory path for every object file - it's been an endless source of bugs.

For now, you'll need to adjust the path to account for that, maybe something like:
-Wl,-Map=../../$(BIN1).map

I'll look into adding a cleaner option for generating a map file.

**Comment by HiFiPhile** [comment]
> I'll look into adding a cleaner option for generating a map file.

Thank you !

Another thing I'm thinking is avoid adding `.exe` extension while cross-compiling.

**Comment by hirdrac** [comment]
you can try testing these changes to lines 601,602:
```
override _gen_bin_name = $(_$1_bdir)$($2)$(_$1_bsfx)
override _gen_bin_aliases = $(if $(_$1_bdir),$($2)$(_$1_sfx)) $(if $(_binext),$(_$1_bdir)$($2)$(_$1_bsfx)$(_binext))

```
I don't remember why I explicitly added .exe to the end of window's binary names - it seems to work fine without it.

**Comment by HiFiPhile** [comment]
> you can try testing these changes to lines 601,602:

Tested with `gcc version 12.2.0 (Rev10, Built by MSYS2 project)`, `.exe` is correctly added to native build. also `make clean` & `make clobber` work.

**Comment by hirdrac** [comment]
Try this file:
https://github.com/hirdrac/gx_lib/blob/main/Makefile.mk

for your Makefile, add:
BIN1.OPTIONS = mapfile

**Comment by HiFiPhile** [comment]
Did the test, it works well !

**Comment by hirdrac** [comment]
I'll eventually have these changes in the main project for the next release - thanks for all your feedback.
